### ISSUE TITLE
部署后在浏览器打开报错

### ISSUE THREAD

**Issue by ppp1234** [PierXuY/ChatGPT-Assistant#2]
在腾讯云服务器上部署后，streamlit显示已经运行，但：
1、ie、edge打开页面均显示空白，见下方截图，其中edge我试了多个版本，都是这样。
2、firefox、chrome可以打开页面，但是无法载入语音模块，报错见截图。

![微信截图_20230603003108](https://github.com/PierXuY/ChatGPT-Assistant/assets/21018874/83fe8a39-de48-4fd1-a4d4-2a4dbb99c815)

![微信截图_20230603003018](https://github.com/PierXuY/ChatGPT-Assistant/assets/21018874/9eb7da8a-4908-4586-b89f-fc47323a9cda)

**Comment by PierXuY** [comment]
这个部署在streamlit cloud的公开项目 https://pearxuy-gpt.streamlit.app/ 你那边能正常加载吗？ 如果不能的话，那就是浏览器端的问题，建议重新安装最新版Edge或Chrome。否则就可能是后端云服务器的问题，记得按照requirements.txt中指定的版本安装，方便的话，请提供下浏览器控制台中的报错信息。

**Comment by ppp1234** [comment]
>  https://pearxuy-gpt.streamlit.app/ 可以正常访问，chrome浏览器可以打开并正常使用。
反思下我自己搭建的环境：
1、我搭建了在了海外的腾讯云服务器上，服务器用的是win2012，直接在windows下部署的
2、我用的pyhton版本是3.11.2（方便告知下您那部署时的python版本么？）
3、pip的依赖都是按照requirements.txt中的指定版本安装的，都检查过了。
streamlit==1.20.0
openai==0.27.0
pandas==1.5.3
requests==2.28.2
4、浏览器console报错

crack.js:1 super_copy_cracked:false
DevTools failed to load source map: Could not load content for chrome-extension://cofdbpoegempjloogbagkncekinflcnj/build/content.js.map: 系统错误: net::ERR_BLOCKED_BY_CLIENT
43.153.78.251/:1 Uncaught (in promise) UNAUTHORIZED
Promise.then（异步）
（匿名） @ search-helper.js:21669
（匿名） @ search-helper.js:9588
main.8a695abc.js:2 Gather usage stats:  true
main.8a695abc.js:2     GET https://cdn.segment.com/analytics.js/v1/iCkMy7ymtJ9qYzQRXkQpnAJEq7D4NyMU/analytics.min.js net::ERR_BLOCKED_BY_CLIENT
e.load @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
value @ main.8a695abc.js:2
o.handleOneTimeInitialization @ main.8a695abc.js:2
o.handleNewSession @ main.8a695abc.js:2
newSession @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
o.handleMessage @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
d @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
Promise.then（异步）
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
e.mark.wrap.websocket.onmessage @ main.8a695abc.js:2
main.8a695abc.js:2 Unrecognized feature: 'ambient-light-sensor'.
z @ main.8a695abc.js:2
uu @ main.8a695abc.js:2
xs @ main.8a695abc.js:2
ks @ main.8a695abc.js:2
qs @ main.8a695abc.js:2
_s @ main.8a695abc.js:2
gs @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
t.unstable_runWithPriority @ main.8a695abc.js:2
Zo @ main.8a695abc.js:2
Ko @ main.8a695abc.js:2
$o @ main.8a695abc.js:2
fs @ main.8a695abc.js:2
enqueueSetState @ main.8a695abc.js:2
m.setState @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
setTimeout（异步）
o.handleDeltaMsg @ main.8a695abc.js:2
delta @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
o.handleMessage @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
d @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
Promise.then（异步）
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
e.mark.wrap.websocket.onmessage @ main.8a695abc.js:2
main.8a695abc.js:2 Unrecognized feature: 'battery'.
z @ main.8a695abc.js:2
uu @ main.8a695abc.js:2
xs @ main.8a695abc.js:2
ks @ main.8a695abc.js:2
qs @ main.8a695abc.js:2
_s @ main.8a695abc.js:2
gs @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
t.unstable_runWithPriority @ main.8a695abc.js:2
Zo @ main.8a695abc.js:2
Ko @ main.8a695abc.js:2
$o @ main.8a695abc.js:2
fs @ main.8a695abc.js:2
enqueueSetState @ main.8a695abc.js:2
m.setState @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
setTimeout（异步）
o.handleDeltaMsg @ main.8a695abc.js:2
delta @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
o.handleMessage @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
d @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
Promise.then（异步）
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
e.mark.wrap.websocket.onmessage @ main.8a695abc.js:2
main.8a695abc.js:2 Unrecognized feature: 'document-domain'.
z @ main.8a695abc.js:2
uu @ main.8a695abc.js:2
xs @ main.8a695abc.js:2
ks @ main.8a695abc.js:2
qs @ main.8a695abc.js:2
_s @ main.8a695abc.js:2
gs @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
t.unstable_runWithPriority @ main.8a695abc.js:2
Zo @ main.8a695abc.js:2
Ko @ main.8a695abc.js:2
$o @ main.8a695abc.js:2
fs @ main.8a695abc.js:2
enqueueSetState @ main.8a695abc.js:2
m.setState @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
setTimeout（异步）
o.handleDeltaMsg @ main.8a695abc.js:2
delta @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
o.handleMessage @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
d @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
Promise.then（异步）
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
e.mark.wrap.websocket.onmessage @ main.8a695abc.js:2
main.8a695abc.js:2 Unrecognized feature: 'layout-animations'.
z @ main.8a695abc.js:2
uu @ main.8a695abc.js:2
xs @ main.8a695abc.js:2
ks @ main.8a695abc.js:2
qs @ main.8a695abc.js:2
_s @ main.8a695abc.js:2
gs @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
t.unstable_runWithPriority @ main.8a695abc.js:2
Zo @ main.8a695abc.js:2
Ko @ main.8a695abc.js:2
$o @ main.8a695abc.js:2
fs @ main.8a695abc.js:2
enqueueSetState @ main.8a695abc.js:2
m.setState @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
setTimeout（异步）
o.handleDeltaMsg @ main.8a695abc.js:2
delta @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
o.handleMessage @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
d @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
Promise.then（异步）
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
e.mark.wrap.websocket.onmessage @ main.8a695abc.js:2
main.8a695abc.js:2 Unrecognized feature: 'legacy-image-formats'.
z @ main.8a695abc.js:2
uu @ main.8a695abc.js:2
xs @ main.8a695abc.js:2
ks @ main.8a695abc.js:2
qs @ main.8a695abc.js:2
_s @ main.8a695abc.js:2
gs @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
t.unstable_runWithPriority @ main.8a695abc.js:2
Zo @ main.8a695abc.js:2
Ko @ main.8a695abc.js:2
$o @ main.8a695abc.js:2
fs @ main.8a695abc.js:2
enqueueSetState @ main.8a695abc.js:2
m.setState @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
setTimeout（异步）
o.handleDeltaMsg @ main.8a695abc.js:2
delta @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
o.handleMessage @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
d @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
Promise.then（异步）
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
e.mark.wrap.websocket.onmessage @ main.8a695abc.js:2
main.8a695abc.js:2 Unrecognized feature: 'oversized-images'.
z @ main.8a695abc.js:2
uu @ main.8a695abc.js:2
xs @ main.8a695abc.js:2
ks @ main.8a695abc.js:2
qs @ main.8a695abc.js:2
_s @ main.8a695abc.js:2
gs @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
t.unstable_runWithPriority @ main.8a695abc.js:2
Zo @ main.8a695abc.js:2
Ko @ main.8a695abc.js:2
$o @ main.8a695abc.js:2
fs @ main.8a695abc.js:2
enqueueSetState @ main.8a695abc.js:2
m.setState @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
setTimeout（异步）
o.handleDeltaMsg @ main.8a695abc.js:2
delta @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
o.handleMessage @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
d @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
Promise.then（异步）
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
e.mark.wrap.websocket.onmessage @ main.8a695abc.js:2
main.8a695abc.js:2 Unrecognized feature: 'vr'.
z @ main.8a695abc.js:2
uu @ main.8a695abc.js:2
xs @ main.8a695abc.js:2
ks @ main.8a695abc.js:2
qs @ main.8a695abc.js:2
_s @ main.8a695abc.js:2
gs @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
t.unstable_runWithPriority @ main.8a695abc.js:2
Zo @ main.8a695abc.js:2
Ko @ main.8a695abc.js:2
$o @ main.8a695abc.js:2
fs @ main.8a695abc.js:2
enqueueSetState @ main.8a695abc.js:2
m.setState @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
setTimeout（异步）
o.handleDeltaMsg @ main.8a695abc.js:2
delta @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
o.handleMessage @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
d @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
Promise.then（异步）
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
e.mark.wrap.websocket.onmessage @ main.8a695abc.js:2
main.8a695abc.js:2 Unrecognized feature: 'wake-lock'.
z @ main.8a695abc.js:2
uu @ main.8a695abc.js:2
xs @ main.8a695abc.js:2
ks @ main.8a695abc.js:2
qs @ main.8a695abc.js:2
_s @ main.8a695abc.js:2
gs @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
t.unstable_runWithPriority @ main.8a695abc.js:2
Zo @ main.8a695abc.js:2
Ko @ main.8a695abc.js:2
$o @ main.8a695abc.js:2
fs @ main.8a695abc.js:2
enqueueSetState @ main.8a695abc.js:2
m.setState @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
setTimeout（异步）
o.handleDeltaMsg @ main.8a695abc.js:2
delta @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
o.handleMessage @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
d @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
Promise.then（异步）
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
e.mark.wrap.websocket.onmessage @ main.8a695abc.js:2
6An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
index.html:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
/component/voice_toolkit.voice_toolkit/index.html?streamlitUrl=http%3A%2F%2F43.153.78.251%2F:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
index.html:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
index.html:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
index.html:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
about:srcdoc:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
main.8a695abc.js:2     GET http://43.153.78.251/static/js/279.b3d7df7a.chunk.js net::ERR_EMPTY_RESPONSE
__webpack_require__.l @ main.8a695abc.js:2
__webpack_require__.f.j @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
__webpack_require__.e @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
C @ main.8a695abc.js:2
Gu @ main.8a695abc.js:2
ks @ main.8a695abc.js:2
qs @ main.8a695abc.js:2
_s @ main.8a695abc.js:2
gs @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
t.unstable_runWithPriority @ main.8a695abc.js:2
Zo @ main.8a695abc.js:2
Ko @ main.8a695abc.js:2
$o @ main.8a695abc.js:2
fs @ main.8a695abc.js:2
enqueueSetState @ main.8a695abc.js:2
m.setState @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
setTimeout（异步）
o.handleDeltaMsg @ main.8a695abc.js:2
delta @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
o.handleMessage @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
d @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
Promise.then（异步）
r @ main.8a695abc.js:2
u @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
e.mark.wrap.websocket.onmessage @ main.8a695abc.js:2
main.8a695abc.js:2 ChunkLoadError: Loading chunk 279 failed.
(error: http://43.153.78.251/static/js/279.b3d7df7a.chunk.js)
    at __webpack_require__.f.j (main.8a695abc.js:2:4427444)
    at main.8a695abc.js:2:4423627
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (main.8a695abc.js:2:4423574)
    at main.8a695abc.js:2:4546370
    at C (main.8a695abc.js:2:2736871)
    at Gu (main.8a695abc.js:2:2471773)
    at ks (main.8a695abc.js:2:2458434)
    at qs (main.8a695abc.js:2:2458362)
    at _s (main.8a695abc.js:2:2458225)
lu @ main.8a695abc.js:2
n.payload @ main.8a695abc.js:2
fi @ main.8a695abc.js:2
Ha @ main.8a695abc.js:2
Gu @ main.8a695abc.js:2
ks @ main.8a695abc.js:2
qs @ main.8a695abc.js:2
_s @ main.8a695abc.js:2
gs @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
t.unstable_runWithPriority @ main.8a695abc.js:2
Zo @ main.8a695abc.js:2
Ko @ main.8a695abc.js:2
N @ main.8a695abc.js:2
z.port1.onmessage @ main.8a695abc.js:2
main.8a695abc.js:2 ChunkLoadError: Loading chunk 279 failed.
(error: http://43.153.78.251/static/js/279.b3d7df7a.chunk.js)
ChunkLoadError: Loading chunk 279 failed.
(error: http://43.153.78.251/static/js/279.b3d7df7a.chunk.js)
    at __webpack_require__.f.j (main.8a695abc.js:2:4427444)
    at main.8a695abc.js:2:4423627
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (main.8a695abc.js:2:4423574)
    at main.8a695abc.js:2:4546370
    at C (main.8a695abc.js:2:2736871)
    at Gu (main.8a695abc.js:2:2471773)
    at ks (main.8a695abc.js:2:2458434)
    at qs (main.8a695abc.js:2:2458362)
    at _s (main.8a695abc.js:2:2458225)
a @ main.8a695abc.js:2
e.componentDidCatch @ main.8a695abc.js:2
i.componentDidCatch.n.callback @ main.8a695abc.js:2
hi @ main.8a695abc.js:2
Mu @ main.8a695abc.js:2
Ts @ main.8a695abc.js:2
t.unstable_runWithPriority @ main.8a695abc.js:2
Zo @ main.8a695abc.js:2
Rs @ main.8a695abc.js:2
gs @ main.8a695abc.js:2
（匿名） @ main.8a695abc.js:2
t.unstable_runWithPriority @ main.8a695abc.js:2
Zo @ main.8a695abc.js:2
Ko @ main.8a695abc.js:2
N @ main.8a695abc.js:2
z.port1.onmessage @ main.8a695abc.js:2
www.google.com/s2/favicons?domain=http://www.baidu.com/:1     GET https://www.google.com/s2/favicons?domain=http://www.baidu.com/ net::ERR_CONNECTION_TIMED_OUT
Image（异步）
generateBookmarksList @ content.js:12
initSidebar @ content.js:5
（匿名） @ content.js:35
Promise.then（异步）
（匿名） @ content.js:34
setTimeout（异步）
（匿名） @ content.js:33
www.google.com/s2/favicons?domain=http://www.google.com/:1     GET https://www.google.com/s2/favicons?domain=http://www.google.com/ net::ERR_CONNECTION_TIMED_OUT
Image（异步）
generateBookmarksList @ content.js:12
initSidebar @ content.js:5
（匿名） @ content.js:35
Promise.then（异步）
（匿名） @ content.js:34
setTimeout（异步）
（匿名） @ content.js:33
www.google.com/s2/favicons?domain=https://www.4d4y.com/forum/forumdisplay.php?fid=2:1     GET https://www.google.com/s2/favicons?domain=https://www.4d4y.com/forum/forumdisplay.php?fid=2 net::ERR_CONNECTION_TIMED_OUT
Image（异步）
generateBookmarksList @ content.js:12
initSidebar @ content.js:5
（匿名） @ content.js:35
Promise.then（异步）
（匿名） @ content.js:34
setTimeout（异步）
（匿名） @ content.js:33
www.google.com/s2/favicons?domain=https://bbs.eastgame.org/:1     GET https://www.google.com/s2/favicons?domain=https://bbs.eastgame.org/ net::ERR_CONNECTION_TIMED_OUT
Image（异步）
generateBookmarksList @ content.js:12
initSidebar @ content.js:5
（匿名） @ content.js:35
Promise.then（异步）
（匿名） @ content.js:34
setTimeout（异步）
（匿名） @ content.js:33
www.google.com/s2/favicons?domain=http://www.chaospace.fun/:1     GET https://www.google.com/s2/favicons?domain=http://www.chaospace.fun/ net::ERR_CONNECTION_TIMED_OUT
Image（异步）
generateBookmarksList @ content.js:12
initSidebar @ content.js:5
（匿名） @ content.js:35
Promise.then（异步）
（匿名） @ content.js:34
setTimeout（异步）
（匿名） @ content.js:33
www.google.com/s2/favicons?domain=https://www.weibo.com/:1     GET https://www.google.com/s2/favicons?domain=https://www.weibo.com/ net::ERR_CONNECTION_TIMED_OUT
Image（异步）
generateBookmarksList @ content.js:12
initSidebar @ content.js:5
（匿名） @ content.js:35
Promise.then（异步）
（匿名） @ content.js:34
setTimeout（异步）
（匿名） @ content.js:33
www.google.com/s2/favicons?domain=https://www.bilibili.com/:1     GET https://www.google.com/s2/favicons?domain=https://www.bilibili.com/ net::ERR_CONNECTION_TIMED_OUT
Image（异步）
generateBookmarksList @ content.js:12
initSidebar @ content.js:5
（匿名） @ content.js:35
Promise.then（异步）
（匿名） @ content.js:34
setTimeout（异步）
（匿名） @ content.js:33
www.google.com/s2/favicons?domain=http://moss.casco.signal/default.aspx:1     GET https://www.google.com/s2/favicons?domain=http://moss.casco.signal/default.aspx net::ERR_CONNECTION_TIMED_OUT
Image（异步）
generateBookmarksList @ content.js:12
initSidebar @ content.js:5
（匿名） @ content.js:35
Promise.then（异步）
（匿名） @ content.js:34
setTimeout（异步）
（匿名） @ content.js:33

**Comment by PierXuY** [comment]
那个项目是基于Python3.9版本部署的，不过3.11我也有部署过，和Python版本的关系应该不大。
论坛里有个[帖子](https://discuss.streamlit.io/t/the-app-is-attempting-to-load-the-component-from-and-hasnt-received-its-streamlit-message/36968/7)和这个报错相同，提到可能和代理设置有关，这个就不太好解决了，我也不熟悉。
方便的话可以用linux系统，比如ubuntu来部署试试。如果用不到语音输入功能的话可以在`功能`模块里关闭，或者在源码里删掉。

**Comment by PierXuY** [comment]
你的上一个回答里有暴露自己服务器的IP地址，安全起见，帮你删除掉了。

**Comment by zhp821** [comment]
![1686350685957](https://github.com/PierXuY/ChatGPT-Assistant/assets/4883604/3fa34003-fc57-47fe-864c-98bdadca802f)

获取语音模块报错，微信和chrome 以及edge都无法加载语音模块

**Comment by PierXuY** [comment]
> 

更新一下浏览器版本试试，可能是当前版本不支持:has伪类选择器
