### ISSUE TITLE
怎么修改能支持azure openai呢?

### ISSUE THREAD

**Issue by chqa** [PierXuY/ChatGPT-Assistant#5]
怎么修改能支持azure openai呢?

**Comment by PierXuY** [comment]
没有使用过，不太清楚。可以查看下相关教程。

**Comment by TsaiRongFu** [comment]
@PierXuY 

推，希望作者能加上這種方式

今天自己嘗試換成azure openai，是有回傳成功但不知道哪裡有問題沒版法顯示回傳內容
