### ISSUE TITLE
submit按钮失效

### ISSUE THREAD

**Issue by yorkqqcom** [PierXuY/ChatGPT-Assistant#9]
部署后 使用时发现 submit按钮失效。
检查后，将
user_input = st.text_area(
            "**输入：**",
替换成
user_input = st.text_area(
            "__输入：__",

submit按钮恢复正常

**Comment by PierXuY** [comment]
我怎么没看出区别呀...

**Comment by yorkqqcom** [comment]
我部署后，在text_area 填写后submit按钮提交无效，ctrl+enter正常。之后将黑体字的表示方式采用 “两个下划线（__）包围文字”后， submit正常。问题原因不清楚。


在Markdown中，黑体字的表示方式可以使用两个星号（**）或包围文字，两个下划线（__）包围文字。


最后感谢您这边的开源，后续打算在此版本上增加excel分析问题功能。
同时阅读了源码，发现使用很多st.rerun()方法，我注释了其中3个st.rerun()方法，目前使用正常，不知会有什么其他影响？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PierXuY/ChatGPT-Assistant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月20日(星期二) 中午12:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PierXuY/ChatGPT-Assistant] submit按钮失效 (Issue #9)





 
我怎么没看出区别呀...

**Comment by PierXuY** [comment]
客气了。 
- submit的问题我这里复现不了，所以也不太清楚。
- 有些st.rerun()可能是出于特殊情况或者是保险考虑，也有可能是后续增加新代码后造就了多余的re.rerun，需要根据具体逻辑来考量。修改源码的时候可以自行考量，多加测试。

**Comment by yorkqqcom** [comment]
可能和浏览器有关。
我这边测试浏览器为 Edge



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月20日(周二) 中午1:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PierXuY/ChatGPT-Assistant] submit按钮失效 (Issue #9)




 
客气了。
  
submit的问题我这里复现不了，所以也不太清楚。
 
有些st.rerun()可能是出于特殊情况或者是保险考虑，也有可能是后续增加新代码后造就了多余的re.rerun，需要根据具体逻辑来考量。修改源码的时候可以自行考量，多加测试。

**Comment by PierXuY** [comment]
测试在Edge上也是正常的，可能和st版本有关系。一直没再更新项目，在最新版本的st适配上确实存在问题。
